version: "3.7"

services:
  mysql:
    image: mysql:5.7.28
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake
      MYSQL_USER: cake_user
      MYSQL_PASSWORD: password
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 33060:3306
  phpfpm:
    build:
      context: .
      dockerfile: ./docker/phpfpm/Dockerfile
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
      #- /var/www/html/vendor
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - phpfpm
    ports:
      - 8080:80
volumes:
  mysql-data:
    driver: local
